"""Add report_file to medical_records

Revision ID: 088df42c989a
Revises: f5f43f8a4ddf
Create Date: 2025-07-01 15:36:06.379976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '088df42c989a'
down_revision: Union[str, Sequence[str], None] = 'f5f43f8a4ddf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medical_records', sa.Column('report_file', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('medical_records', 'report_file')
    # ### end Alembic commands ###
